#!/usr/bin/env python3

import colors as c

print("do you like airsoft")

airsoft = input(">")

if airsoft == "no" or airsoft == "No":
    print("well I like airsoft")


elif airsoft == "yes" or airsoft == "Yes":
    print("do you like lazer tag" )


else:
    print("what was that")
    

